### PR TITLE
Added missing Enums (CW, P, PUNCT) to PosTag so they may be reference…

### PR DESCRIPTION
**Pull request by cogmission**
…d in Java client code

### CODE REVIEW

**Comment by tjagvad** [comment]
Hi David,
The pos tags available on the api are defined in the enum io.cortical.nlp.pos.CorePosTypes.PosTagUniversal in RETINA-SPARK, retina-nlp-model.

It contains the pos tags listed here (Universal POS tags on the left):
http://documentation.cortical.io/working_with_text.html#pos-tags

so the PosTag enum in the client should contain exactly these elements as well.

**Comment by cogmission** [comment]
Hi @tjagvad, Yes that is what it does now? Those 3 were the ones that were missing... I believe?

**Comment by tjagvad** [comment]
Yes, but it should be that set exclusively - some of the tags currently in there are not valid. Just replace everything with the elements in the universal set.

**Comment by tjagvad** [comment]
Otherwise you could send invalid pos tags from the client.

**Comment by cogmission** [comment]
Sorry Soren, I was just paying attention to the ones that were missing. I forgot that it also included ones that were invalid. Ok, should be good now... ;-)

**Comment by tjagvad** [comment]
Looks good!

**Comment by cogmission** [comment]
@tjagvad 
(P.S. The invalid ones don't cause any exception so there is some code on the back end which still includes them?)

Did you see this?

**Comment by tjagvad** [comment]
I did not see this. Is this a client thing? These pos tags are only used for the /text/tokenize right? When I specify for example VBZ as POStags for the text/tokenize function, the api throws an exception.

**Comment by cogmission** [comment]
Maybe I misspoke? Please excuse then, I thought I had tested some that didn't throw an exception or Erik said that they don't... hold on let me check my email (from Erik)?

**Pull request merged**
